# <center> **Factoración de Cholesky** </center>
## <font size=4> **Métodos Numéricos II** </font> <font color=gray size=4> -- Alan Reyes-Figueroa </font>

In [1]:
import numpy as np
from scipy import linalg as lg

In [2]:
from LLT_LDLT import Cholesky, LDLt

## Descomposición de Cholesky

In [3]:
M = np.array([[8.,7,9,5], [7,3,3,1], [9,3,1,0], [5,1,0,8]])
print(M)

[[8. 7. 9. 5.]
 [7. 3. 3. 1.]
 [9. 3. 1. 0.]
 [5. 1. 0. 8.]]


In [4]:
R = Cholesky(M)

Exception: matrix is not positive definite

In [5]:
A = np.array([[4.,-1,1], [-1,4.25,2.75], [1,2.75, 3.5]])
print(A)

[[ 4.   -1.    1.  ]
 [-1.    4.25  2.75]
 [ 1.    2.75  3.5 ]]


In [6]:
R = Cholesky(A)

In [7]:
R

array([[ 2. , -0.5,  0.5],
       [ 0. ,  2. ,  1.5],
       [ 0. ,  0. ,  1. ]])

In [8]:
R.T @ R

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [9]:
lg.cholesky(A)

array([[ 2. , -0.5,  0.5],
       [ 0. ,  2. ,  1.5],
       [ 0. ,  0. ,  1. ]])

In [10]:
L, D = LDLt(A)

In [11]:
print(L)

[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.25  0.75  1.  ]]


In [12]:
print(D)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 1.]]


In [13]:
L @ D @ L.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [14]:
B = np.array([[8.,1,2,4], [1,6,1,3], [2,1,5,0], [4,3,0,7]])
print(B)

[[8. 1. 2. 4.]
 [1. 6. 1. 3.]
 [2. 1. 5. 0.]
 [4. 3. 0. 7.]]


In [15]:
R = Cholesky(B)

In [16]:
lg.eig(B)

(array([13.05517529+0.j,  1.83243025+0.j,  6.03679177+0.j,  5.07560269+0.j]),
 array([[ 0.65002477,  0.47510272,  0.54436109,  0.23540645],
        [ 0.38562664,  0.43983077, -0.61636985, -0.5271899 ],
        [ 0.20926623, -0.43883366,  0.45559036, -0.74570107],
        [ 0.62045752, -0.62309816, -0.34087626,  0.33254252]]))

In [17]:
R.T @ R

array([[ 8.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         4.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  1.00000000e+00,
         3.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00,  5.00000000e+00,
        -2.22044605e-16],
       [ 4.00000000e+00,  3.00000000e+00, -2.22044605e-16,
         7.00000000e+00]])

In [18]:
L, D = LDLt(B)

In [19]:
print(L)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.25000000e-01  1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 2.50000000e-01  1.27659574e-01  1.00000000e+00  0.00000000e+00]
 [ 5.00000000e-01  4.25531915e-01 -2.99516908e-01  1.00000000e+00]]


In [20]:
print(D)

[[8.         0.         0.         0.        ]
 [0.         5.875      0.         0.        ]
 [0.         0.         4.40425532 0.        ]
 [0.         0.         0.         3.5410628 ]]


In [21]:
L @ D @ L.T

array([[8.00000000e+00, 1.00000000e+00, 2.00000000e+00, 4.00000000e+00],
       [1.00000000e+00, 6.00000000e+00, 1.00000000e+00, 3.00000000e+00],
       [2.00000000e+00, 1.00000000e+00, 5.00000000e+00, 1.11022302e-16],
       [4.00000000e+00, 3.00000000e+00, 5.55111512e-17, 7.00000000e+00]])

## Determinar si una matriz es Positiva Definida

In [22]:
def isPositive(A):
    m, n = A.shape
    if (m != n):
        raise Exception('matrix is not square')
    elif not np.all(A.T == A):
        raise Exception('matrix is not symmetric')
    else:
        R = A.copy()    
        for k in range(0, n):
            if (R[k,k] <= 0):
                return False
            else:
                for j in range(k+1, n):
                    R[j,k:n] = R[j,k:n] - (R[k,j] / R[k,k]) * R[k,k:n]
                R[k,k:n] = R[k,k:n] / np.sqrt(R[k,k])
    return True

In [23]:
isPositive(A)

True

In [24]:
isPositive(M)

False

In [25]:
S, V = lg.eig(A)

In [26]:
A

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [27]:
V @ np.diag(np.abs(S)) @ V.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

## Hallar la matriz Definida Positiva más cercana

In [28]:
def nearestPositive(A, eps=1e-16):
    m, n = A.shape
    if (m != n):
        raise Exception('matrix is not square')
    elif not np.all(A.T == A):
        raise Exception('matrix is not symmetric')
    else:
        S, V = lg.eig(A)
        S = np.abs(S)
        S[S <= 0.] = eps  # cambiar autovalores negativos a eps
    return V @ np.diag(S) @ V.T

In [29]:
Ap = nearestPositive(A)

In [30]:
A

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [31]:
C = A.copy()
C[0,0] = 0.
C

array([[ 0.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [32]:
isPositive(C)

False

In [33]:
Cp = nearestPositive(C, eps=1e-16)

In [34]:
Cp

array([[ 1.31600302, -0.39618743,  0.33342399],
       [-0.39618743,  4.52704315,  2.44415954],
       [ 0.33342399,  2.44415954,  3.83763112]])

In [35]:
Mp = nearestPositive(M, eps=1e-16)

In [36]:
Mp

array([[13.02872297,  5.02823558,  3.56008771,  3.36080352],
       [ 5.02823558,  4.23531208,  4.70831055,  1.61579398],
       [ 3.56008771,  4.70831055,  7.27494693,  1.79798065],
       [ 3.36080352,  1.61579398,  1.79798065,  8.53589334]])