# <center> **Eliminación Gaussiana y Factoración LU** </center>
## <font size=4> **Métodos Numéricos II** </font> <font color=gray size=4> -- Alan Reyes-Figueroa </font>

In [5]:
import numpy as np
from scipy import linalg as lg

## Factoración Gaussiana

In [12]:
# Algoritmo de eliminación gaussiana (o factoración LU), en el caso más simple
def gaussianSimple(A):
    ''' Finds the gaussian reduction (U) or the LU factorization of a matrix A.
        Inputs:  A = matrix to reduce, as numpy array of shape (m,n).
        Outputs: L = triangular inferior matrix of row reductions, as numpy array of shape (m,m).
                 U = gaussian reduced matrix in row echelon form, as numpy array of shape (m,n).
    '''
    m, n = A.shape
    U = A.copy()
    L = np.eye(m)

    for k in range(0, m-1):            # iteration over columns
        for j in range(k+1, n):        # iteration over rows after k
            if (U[k,k] != 0):
                L[j,k] = U[j,k] / U[k,k]
                U[j,k:n] = U[j,k:n] - L[j,k]*U[k,k:n]
            else:
                raise Exception('A has no LU factorization')
    return L, U

In [13]:
A = np.array([[8,7,9,5], [4,3,3,1], [2.,1,1,0], [6,7,9,8]])
print(A)

[[8. 7. 9. 5.]
 [4. 3. 3. 1.]
 [2. 1. 1. 0.]
 [6. 7. 9. 8.]]


In [14]:
# descomposición LU
L, U = gaussianSimple(A)

In [15]:
print(L, end='\n\n')

print(U)

[[ 1.    0.    0.    0.  ]
 [ 0.5   1.    0.    0.  ]
 [ 0.25  1.5   1.    0.  ]
 [ 0.75 -3.5  -3.    1.  ]]

[[ 8.   7.   9.   5. ]
 [ 0.  -0.5 -1.5 -1.5]
 [ 0.   0.   1.   1. ]
 [ 0.   0.   0.   2. ]]


In [16]:
L @ U

array([[8., 7., 9., 5.],
       [4., 3., 3., 1.],
       [2., 1., 1., 0.],
       [6., 7., 9., 8.]])

In [17]:
B = np.array([[1,3,2,5], [2,6,3,1], [2.,6,1,0], [-3,-9,7,8]])
print(B)

[[ 1.  3.  2.  5.]
 [ 2.  6.  3.  1.]
 [ 2.  6.  1.  0.]
 [-3. -9.  7.  8.]]


In [18]:
L, U = gaussianSimple(B)

Exception: A has no LU factorization

In [16]:
P

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.linalg.inv(P) @ L @ U

array([[ 1.,  3.,  2.,  5.],
       [ 2.,  6.,  3.,  1.],
       [ 2.,  6.,  1.,  0.],
       [-3., -9.,  7.,  8.]])

In [12]:
C = np.array([[1,3,2,5], [2,6,3,1], [2.,8,1,0], [-3,-9,7,8]])
print(C)

[[ 1.  3.  2.  5.]
 [ 2.  6.  3.  1.]
 [ 2.  8.  1.  0.]
 [-3. -9.  7.  8.]]


In [13]:
P, L, U, _ = gaussianReduction(C)

In [14]:
P

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [15]:
L

array([[  1.,   0.,   0.,   0.],
       [  2.,   1.,   0.,   0.],
       [  2.,   0.,   1.,   0.],
       [ -3.,   0., -13.,   1.]])

In [17]:
np.linalg.inv(P) @ L @ U

array([[ 1.,  3.,  2.,  5.],
       [ 2.,  6.,  3.,  1.],
       [ 2.,  8.,  1.,  0.],
       [-3., -9.,  7.,  8.]])

## Cálculo del Determinante

In [18]:
np.linalg.det(A)

-7.999999999999998

In [19]:
Determinante(A)

-8.0

In [20]:
np.linalg.det(B)

-8.49320613838242e-15

In [21]:
Determinante(B)

0.0

In [22]:
np.linalg.det(C)

-188.0

In [23]:
Determinante(C)

-188.0

## Resolver un sistema $A\mathbf{x} = \mathbf{b}$

In [255]:
def GaussJordan(A):
    m, n = A.shape
    U = A.copy()
    L1 = np.eye(m)
    P1 = np.eye(m)
    L2 = np.eye(m)
    P2 = np.eye(m)
    sign = 1

    # first stage
    #print('Primera Etapa. \n')
    for j in range(0, m-1):
        #print('Paso columna {}: \n'.format(j+1))
        for i in range(j+1, m):
            if (U[j,j] == 0):
                if (U[j+1:m,j].sum() != 0.):
                    k = j+1 + np.argwhere(U[j+1:m,j] != 0.)[0][0]
                    U[[j,k],:] = U[[k,j],:]
                    P1[[j,k],:] = P1[[k,j],:]
                    sign = -sign

            if (U[j,j] != 0.):
                L1[i,j] = U[i,j] / U[j,j]
                U[i,j:] = U[i,j:] - L1[i,j]*U[j,j:]
            #print(L1, end='\n\n')
            #print(U, end='\n\n')

    # diagonal
    for j in range(0, m):
        if (U[j,j] != 0.):
            L1[j,j] = 1. / U[j,j]
            U[j,:] = U[j,:] / U[j,j]
        
    # second stage
    #print('Segunda Etapa. \n')
    for j in range(1, m)[::-1]:
        #print('Paso columna {}: \n'.format(j+1))
        for i in range(0, j):
            if (U[j,j] == 0):
                if (U[0:j,j].sum() != 0.):
                    k = np.argwhere(U[0:j,j] != 0.)[0][0]
                    U[[j,k],:] = U[[k,j],:]
                    P2[[j,k],:] = P2[[k,j],:]
                    sign = -sign

            if (U[j,j] != 0.):
                L2[i,j] = U[i,j] / U[j,j]
                U[i,:] = U[i,:] - L2[i,j]*U[j,:]
            #print(L2, end='\n\n')
            #print(U, end='\n\n')

    return U

In [24]:
b = np.array([0., 1, 0, 0])

In [25]:
x = SolveAxb(A, b)
x

array([-0.75,  2.5 , -1.  , -0.5 ])

## Cálculo de la inversa

In [257]:
I = np.eye(A.shape[0])
# matriz extendida
H = np.hstack([A,I])
H

array([[8., 7., 9., 5., 1., 0., 0., 0.],
       [4., 3., 3., 1., 0., 1., 0., 0.],
       [2., 1., 1., 0., 0., 0., 1., 0.],
       [6., 7., 9., 8., 0., 0., 0., 1.]])

In [259]:
U = GaussJordan(H)
np.round(U, 3)

array([[ 1.  ,  0.  ,  0.  ,  0.  , -0.25, -0.75,  2.25,  0.25],
       [-0.  ,  1.  ,  0.  ,  0.  , -0.5 ,  2.5 , -3.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  1.  , -1.  , -0.5 , -0.5 ],
       [ 0.  ,  0.  ,  0.  ,  1.  , -0.5 , -0.5 ,  1.5 ,  0.5 ]])

In [27]:
iA = np.round(np.linalg.inv(A), 3)
iA

array([[-0.25, -0.75,  2.25,  0.25],
       [-0.5 ,  2.5 , -3.  , -0.  ],
       [ 1.  , -1.  , -0.5 , -0.5 ],
       [-0.5 , -0.5 ,  1.5 ,  0.5 ]])

In [28]:
Inversa(A)

array([[-0.25, -0.75,  2.25,  0.25],
       [-0.5 ,  2.5 , -3.  ,  0.  ],
       [ 1.  , -1.  , -0.5 , -0.5 ],
       [-0.5 , -0.5 ,  1.5 ,  0.5 ]])

In [29]:
A @ iA

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
iA @ A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])